spring:
  config:
    import: "aws-parameterstore:/fix-and-test-v2/prod/"

  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PWD}

  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: ${BUCKET_URL}

  servlet:
    multipart:
      max-file-size: 10MB

# JWT
jwt:
  secret:
    key: ${PROD_JWT_KEY}

server:
  port: 8080

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true

info:
  app:
    name: fix-and-test-v2
    version: 1.0.0
    description: fix-and-test V2 API
